### ISSUE TITLE
Does the AppImage have Cloud integrated?

### ISSUE THREAD

**Issue by petrisch** [opencomputeproject/CADCloud#12]
Mine is the FreeCAD_0.19-23546-Linux-Conda_glibc2.12-x86_64.AppImage
Which is the "latest" I can find. However, when I import Cloud, it doesn't find it. So i guess its not in there right?
Or is it in a specific workbench i have to load?
Your suggesting to use snap instead, is that the way to go? I don't use that until now, but that's just me :-)
Great work btw!!

**Comment by vejmarie** [comment]
Unfortunately, I do not think that Appimage has cloud activated. I am working currently at getting homebrew fully activated. The workbench needs to be explicitly mentioned during compilation (-DBUILD_CLOUD=1). I am willing to make it a default for 0.2. Right now we are under the process to release 0.19 and as this is a new feature I didn't wanted to break the build, and force the dependencies to be integrated (even if windows library now do integrate SSL). Can you switch to homebrew ?

**Comment by petrisch** [comment]
Haven't tried homebrew yet, but I am willing to give a try. What I see is, that there is FreeCad v18 on homebrew. I don't know how to build the latest.
Anyway, I gave the snap install a try, and that works.
However the upload didn't work. 
Should `Cloud.save(part)` give any feedback if it fails?

**Comment by vejmarie** [comment]
Do not take 0.18 but use the tap which is here [https://github.com/FreeCAD/homebrew-freecad](url) especially if you are running big_sur. Cloud workbench is a 0.19 extension.
The error processing into the Cloud workbench is a pity, we still have a lot of work to implement end user feedback from command outcome. Can you give me all the command that you use before the Cloud.save one's ? Normally you have to setup your URL and TCPPort for the CADCloud server, as well as your credential (I don't need their exact value, but need to see how you type them in). As an example when I am calling Cloud.save I am using something like Cloud.save(u"part") (quote and type are important ;))

**Comment by petrisch** [comment]
`import Cloud`
`Cloud.URL(u"https://justyour.parts")`
`Cloud.TCPPort(u":443")`
`Cloud.TokenAuth(u"thetokenihavefromthesite")`
`Cloud.TokenSecret(u"thesecretihavefromthesite")`
`Cloud.Save(u"Pinephone-Case")`

I had a STP Imported and also tried to safe as FreeCAD format.
I pasted all the lines one by one. None gave feedbak, which is ok, just saying. :-)

Well is already offtopic, so sorry.
big_sur? Is that Mac? I'll give brew a try later.
Now i am on the latest snap install, that should work.

**Comment by vejmarie** [comment]
can you change the file name from Cloud.Save(u"Pinephone-Case") to Cloud.Save(u"pinephonecase"), just to check. What is your login name on the server as I could have a look into the logs ?

**Comment by petrisch** [comment]
ok, just did that.
Its the same as here ;-)

**Comment by vejmarie** [comment]
ok, Cloud.TCPPort(u":443") shall be Cloud.TCPPort(u"443") I think

**Comment by petrisch** [comment]
Oh silly me, thanks!
I think i can tell, by the time it took the save command, and by the latency on the web page, that it did something.
But i can't see it in hot topics. Maybe i have just to wait.

**Comment by vejmarie** [comment]
we are progressing ;). The bad news is that I do not see the data on the server. So something wrong happened. Can you launch freecad from a terminal and tell me if you see any error message into it when running the save command ? I suspect either a name resolution issue, or something else.

**Comment by vejmarie** [comment]
@petrisch if you want you can join our discord group https://discord.gg/Z4pBcsM32N

**Comment by petrisch** [comment]
I'm not on discourse, but again, that might will happen later.
The important message is: "The access key ID you provided does not exist in our records."
However i checked the credentials, they are correct.
Now I tried with single quotes, which gave "curl_easy_perform() failed: Couldn't connect to server"
And now the website seem broken, sorry if it was me ;-)

**Comment by vejmarie** [comment]
I just restarted the service. Can you give it back a try. We will see if it crash back ;).

**Comment by petrisch** [comment]
Looks like a success 👍 
You can close that issue.
